### ISSUE TITLE
Handling main arguments

### ISSUE THREAD

**Issue by YaZko** [vellvm/vellvm#104]
We currently do not have a story for main arguments.
The TopLevel provides default values to both _argc_ and _argv_ and feed them to the main. 
But this had the side effect to require programs to take these two as arguments to their main, since [denote_function] checks that the number of arguments provided to the function maps the prototype.

Commit 46944299c39d59f9911c56029daa56f11d4624a6 disabled this check to allow running main functions with no arguments. However, this is unsafe.

Short term TODO: plug back the failure in [combine_lists_err] and move the relaxation on provided arguments to [TopLevel].

Longer term TODO: handle properly main arguments.

**Comment by Zdancewic** [comment]
We had put in some hack to allow illegal test cases (probably declared like `void main()` rather than `i32 main(i32 argc, i8** argv)`) to run, but now the testing framework should be ported to use the `ASSERT EQ` style, which doesn't suffer from this problem.

The right fix is to make sure that all test cases are valid LLVM IR code and, if they use `main` that its declaration type should be correct.  

With a bit more work, the interpreter could take actual command-line arguments.
