### ISSUE TITLE
bad type for constant int

### ISSUE THREAD

**Issue by vzaliva** [vellvm/vellvm#105]
The attached program gives "bad type for constant int" error. *clang* happily compiles it.

[test_ireduction.ll.txt](https://github.com/vellvm/vellvm/files/3726069/test_ireduction.ll.txt)

**Comment by YaZko** [comment]
Hmm indeed we were providing the wrong type to `denote_exp` when evaluating the arguments of a call. It's fixed in 0d12d9165997c3626be19052972a3bf3da733ea5, but please fast-forward to the head, I also fixed a couple of unrelated issue on the way.

This file is not yet solved though, for some reason the load `%tv3 = load double, double* %l1, align 8` loads a float instead of a double, causing a failure at the `fadd` operation. I'll fix this asap.

**Comment by YaZko** [comment]
The last commits fixed the remaining bug for this file: it manipulates underdefined values and the concretization handler for double was wrongly casting the value into a float.

It now passes and agrees with clang.

**Comment by vzaliva** [comment]
seems to be working now. Thanks!
