### ISSUE TITLE
EXP_Integer size

### ISSUE THREAD

**Issue by vzaliva** [vellvm/vellvm#127]
Now integer constants in `EXP_Integer` are of type `Z` and as such are unbounded. However, when they represent fixed-size LLVM integer, there is no guarantee they will fit. In contrast `dvalue` distinguish `DVALUE_I64`, `DVALUE_I32`, etc. which hold the values of `int64` and `int32` respectively.

Perhaps we should approach them similar to `EXP_Float` and `EXP_Double` which have a fixed size. This will ensure the correct constants' sizes in AST by typing system. If there are integer literals that do not fit the expected integer size that could be detected during parsing.

**Comment by YaZko** [comment]
I am confused. `EXP_Integer` has always taken a bounded integer as argument, never a `Z`? 
Am I missing something or was this an error and can be closed?

**Comment by vzaliva** [comment]
See LLVMAst.v:

```
Definition int := Z.
....
| EXP_Integer (x:int)
```
It is unbounded. Perhaps the name `int` is misleading.

**Comment by YaZko** [comment]
Oh right sorry I went through the PRs too fast. We cannot enforce them at parsing time since llvm supports arbitrary sized integers. I don't think having a preprocessing phase after the parsing makes any sense either, that would just be a pain to propagate and reason about everywhere without bringing much benefit. They are just handled in the semantics where we have the typing information and all the finite integers in scope to be treated adequately.

So no I think it makes perfect sense as is. If you were to want to actively reject statically a program that syntactically declare a constant out of the range of its type, you can code a static analysis to this end, but that's not the responsibility of the syntax nor semantics.

**Comment by YaZko** [comment]
The question makes more sense in the context of #142 I think. I'll close this one if that's alright.
