### ISSUE TITLE
Compiling Vellvm raises an error 

### ISSUE THREAD

**Issue by aqjune** [vellvm/vellvm#137]
Hi,
Compiling Vellvm raises a following error:

```
COQC coq/Handlers/Memory.v
File "./coq/Handlers/Memory.v", line 512, characters 8-49:
Error: Tactic failure:  Cannot find witness.

make[1]: *** [coq/Handlers/Memory.vo] Error 1
make: *** [all] Error 2
```

The version of Coq I'm using is 8.10.0.

**Comment by YaZko** [comment]
Hello @aqjune ,
This looks like a failure of lia, that got improved recently. 
If upgrading to 8.11 is not an issue for you then that would almost certainly solve the issue. Otherwise I will take a look Tomorrow to be compatible with 8.10, we should be able to remain compatible with it fairly easily.
Best,
Yannick

**Comment by aqjune** [comment]
I'll try 8.11, thanks!

**Comment by aqjune** [comment]
It works great, thank you.
