### ISSUE TITLE
`memcpy_8_decl` is missing from `defined_intrinsics`

### ISSUE THREAD

**Issue by vzaliva** [vellvm/vellvm#138]
I've noticed that it is in `defined_intrinsics_decls` but not `defined_intrinsics`.
At a quick glance, I could not find the corresponding  `semantic_function` definition to add it.

**Comment by YaZko** [comment]
This is because `memcpy` is an impure intrinsics, it depends on the memory model. 

Only "pure ones" (such as mathematical computations) are implemented with a `semantic_function` and handled early on in the stack of interpretation. Others are handled as part of the memory model, i.e. in `Handlers/Memory.v`, which is the case for `memcpy`.
