### ISSUE TITLE
interp_memory_correct

### ISSUE THREAD

**Issue by Chobbes** [vellvm/vellvm#258]
Found another important admit in `MemoryInterpreters.v`. `interpreter_sound` in `TopLevelRefinements.v` depends upon `interp_memory_correct`.

**Comment by euisuny** [comment]
(As discussed in Slack. Repeating myself here for documentation & longevity) 

The current definition of `interp_memory_prop` is incorrect.

The definition is as follows:

```
Definition interp_memory_prop {R} (RR : R -> R -> Prop) :
      itree Effin R -> MemStateFreshT (PropT Effout) R :=
      fun (t : itree Effin R) (sid : store_id) (ms : MemState) 
          (t' : itree Effout (MemState * (store_id * R))) =>
        interp_prop (OOM := void1) (fun T (e : Effin T) (t : itree Effout T) => exists (sid' : store_id) (ms' : MemState),
               @interp_memory_prop_h T e sid ms (fmap (fun (x : T) => (ms', (sid', x))) t)) RR t ((fmap (fun '(_, (_, x)) => x) t') : itree Effout R).
```
But as we can see from the last snippet `fmap (fun '(_, (_, x)) => x) t'`, we are ignoring the state of the program. This is incorrect, because we must thread through the state as we’re giving a propositional interpretation to a stateful program.

More concretely, we need a version of `interp_prop` where the signature for `h_spec` is not `(h_spec : E ~> PropT F)` but rather `(h_spec : E ~> MemStateFreshT (PropT Effout))`
