### ISSUE TITLE
Prove refine_OOM_h_transitive in OOM.v

### ISSUE THREAD

**Issue by Chobbes** [vellvm/vellvm#320]
```
  #[global] Instance refine_OOM_h_transitive {R} {RR : relation R} `{Transitive _ RR} : Transitive (refine_OOM_h RR).
```

**Comment by euisuny** [comment]
Transitivity for the following case does not work:

`refine_OOM_h RR (Vis e k) (Ret x) -> refine_OOM_h RR (Ret x) (Ret y) -> refine_OOM_h RR (Vis e k) (Ret y)`

Because the continuation specification `oom_k_spec` expects a relation over the continuation over exact equality (i.e. using `eutt eq`), but the we do not know that the `x` and `y` are not exactly equal, in fact they are only related by the relation `RR`. It's necessary to extend the specification for the continuation to relate the continuations by an arbitrary relation `RR`.

**Comment by Chobbes** [comment]
Ah, yeah, you're totally right. I think `oom_k_spec` needs to use `eutt RR`. That's hopefully not a problem, though?

**Comment by euisuny** [comment]
The signatures are mismatched for `k_spec_correct` when using a `k_spec` parameterized by a relation `RR`. 

In order to properly instantiate `interp_prop` with this concrete instances (that can take in an arbitrary relation for its parameterized return types), the signatures for `k_spec` needs to be generalized in this manner:

`k_spec : forall T R, E T -> itree F T -> (T -> itree F R) -> itree F R -> Prop)`

`k_spec : forall T R (RR: relation R), E T -> itree F T -> (T -> itree F R) -> itree F R -> Prop)`

Since this seems like a large change to the definition of `interp_prop` and since this instance isn't used anywhere, I suggest closing this issue.
