### ISSUE TITLE
32-bit floating point values support

### ISSUE THREAD

**Issue by vzaliva** [vellvm/vellvm#73]
Currently only 64-bit float values are supported:

```
EXP_Float (f:float)
```

where

```
Definition float := Floats.float.  (* 64-bit floating point value *)
```

LLVM documentation states that all platforms must 32 and 64-bit floats. It is a good idea for VELLVM to support both. Other floating point sizes are supported by LLVM but are optional.

**Comment by Zdancewic** [comment]
Ah -- right.  I forgot that we didn't support both.  I believe that the starting point is as simple as defining:

```
Definition double := Floats.float.  (* 64-bit floating point value *)
Definition float := Floats.float32.  (* 64-bit floating point value *)
```

We need to push through the changes in LLVMAst, the parser, and the operational semantics.

**Comment by Zdancewic** [comment]
I was wrong.  The semantics does indeed already support both 32- and 64-bit floating point.  The parser, however, always parses into 64 bit format (because we don't know at parsing time what size the constant is supposed to be).  There could be an issue with converting 32-bit literals from their 64-bit literal representation if it is not the case that 32-bit floats are strictly included in 64-bit floats.  

The rest of the semantics pipeline could have problems with floats, but we will definitely support both bit widths.

**Comment by vzaliva** [comment]
so, the `exp` is always `EXP_Float` for both float and doubles. The only way to distinguish them is in `texp` when it is paired with type?

**Comment by Zdancewic** [comment]
That's right -- for parsing purposes, we currently parse all literals as 
though they were 64-bit doubles.  The evaluator, eval_exp, takes a type 
which determines whether the literal is treated as 32 or 64 bit.  From 
what I can tell, the 32-bit literals that are expressible as 64-bit 
values are a complete subset and there is no precision loss when 
converting between them.

--Steve
