### ISSUE TITLE
ill_typed-fop

### ISSUE THREAD

**Issue by vzaliva** [vellvm/vellvm#74]
```
$ ./vellvm -v -interpret ../tests/failing/binop_plus.ll         11:22:35
(* -------- Vellvm Test Harness -------- *)
platform = OS X
Processing: ../tests/failing/binop_plus.ll
* processing file: ../tests/failing/binop_plus.ll
Fatal error: exception Failure("ERROR: ill_typed-fop")
```

Examining the code, there is only one floating point binary operation there:

```
  %l5 = load double, double* %l2, align 8
  %l6 = load double, double* %l3, align 8
  %l7 = fadd double %l5, %l6
```

It looks perfectly normal and all types match. It looks like a bug.

**Comment by Zdancewic** [comment]
My recent commits fix this issue.  The problem was serializing/deserializing floating-point values through the memory model.  There are still some issues with the floating-point computation somewhere, but this isn't the problem.

AH -- the platform stuff is left over from the compilers class that I teach.  I think that OS X and linux look the same from the point of view of the compiler.  I can clean that up at some point :-)
