### ISSUE TITLE
Fix string compare (in AstLib.v)

### ISSUE THREAD

**Issue by Zdancewic** [vellvm/vellvm#75]
The string comparison operation used to implement the identifier environment is very slow.  I suspect that it is because "compare" builds proofs that are very large.  The issue shows up when calling `lookup_id` with a long identifier such as: `llvm.memcpy.p0i8.p0i8.i32`.  Because characters are represented as lists of bits and strings are represented as lists of characters, the proof of LT for such an object is probably huge.

The issue could potentially be with the use of Program Fixpoint to define the string compare.

**Comment by vzaliva** [comment]
I had a similar problem in my compiler. In Coq doing "match" on strings is super-slow. It is decomposed to very complex matches on nested `cons`. The solution to use `string_dec`. By the way, I've developed a small coq plugin just for this. If you do not mind Template-Coq dependency, it might come handy:  https://github.com/vzaliva/coq-switch (available via OPAM)

**Comment by gmalecha** [comment]
I assume that the reason that you are using this particular signature (rather the the non-dependent one) is because you are relying on one of the map functors in the standard library? I'm not sure if there is a reasonable way around this. ExtLib does have finite maps that do not rely on the dependent versions, but they don't have nearly as many lemmas.

**Comment by Zdancewic** [comment]
Switching to the weak fmap (which only requires decidable equality) made things go a lot faster, so the problem must have been in building the proofs for `compare`.
