### ISSUE TITLE
Add infrastructure for external functions

### ISSUE THREAD

**Issue by vzaliva** [vellvm/vellvm#79]
It would be nice to have a way to deal with external functions uniformly. This involves:

1. Getting their toplevel definitions to generate "extern" declarations
2. Supporting lemmas for semantics proofs
3. Coq definitions for interpretation

Additionally, it would be nice if Vellvm user could add support for his own functions without modifying Vellvm sources. For example by passing a dictionary with definitions to the interpreter.

**Comment by Zdancewic** [comment]
There is an (orthogonal) issue that will help: once the testing infrastructure is a bit more robust, it will be easier to add test cases for newly created intrinsics.

**Comment by vzaliva** [comment]
Awesome! I will take a closer look. A couple of quick questions:

1. To use intrinsics I need to generate "external" top-level definitions for them. Is it possible to have this as a part of this framework? Generating them manually is error-prone. 

2. Do we plan to move other built-in intrinsics (e.g. `llvm.memcpy.p0i8.p0i8.i32`) to this framework or we will keep them hardcoded? It is especially interesting in relation to my previus point. Having all intrinsics in the same framework will allow me to easily generate top-level extern definitions.

**Comment by Zdancewic** [comment]
For (1): I think that this should be possible.  What do you have in mind to make this easier?  We can define a datastructure that bundles together the TLE_Declaration with the information needed for the intrinsics definition, but it has to live inside a functor (see Intrinsics.v), which might make it a bit annoying.

For (2): we can't easily move the memory-model dependent intrinsics into this framework because their implementation needs internal access to the memory representation.  For now, we should probably just add such intrinsics directly.  However, it would be possible for the memory model to provide the list of intrinsic declarations that it provides so that clients can just use those rather than having to generate them themselves.

**Comment by Zdancewic** [comment]
OK -- I've merged the intrinsics branch into master.  We can see how this works for now.
