### ISSUE TITLE
Refactor Error in Semantics

### ISSUE THREAD

**Issue by Zdancewic** [vellvm/vellvm#83]
We should remove the notion of failure from the Trace monad and instead lift it to the toplevel, so that we have, e.g.

```
Fixpoint eval_exp (top:option dtyp) (o:exp) {struct o} : err (Trace dvalue) :=
```

And corresponding changes throughout StepSemantics.

**Comment by Chobbes** [comment]
- Find out what we want to do on debug
- Work on master.

**Comment by Chobbes** [comment]
Hmmm. There was some suggestion that this was previously the case, however looking at the changes even a year ago `eval_exp` had a result type of `Trace dvalue`.

I bring this up because there's a few places where it seems like I'm going to have to commute `Trace` and `err`. E.g., I have to go from a `Trace (err dvalue)` to an `err (Trace dvalue)` (for instance this would be helpful in the `OP_IBinop` case of `eval_exp`).

I'm not sure if this is trivial (I'll look into it more tomorrow). But I suspect this may be problematic because Trace is coinductive and err is inductive. Previously when in a similar situation we introduced `mfix`, however if the types are any indication it seems like that would only help when going from `err (Trace dvalue)` to `Trace (err dvalue)`.

Am I missing something obvious?

**Comment by YaZko** [comment]
Clearly as you say a general function converting a `itree (IO + failure) (err dvalue)` to an `err (itree IO dvalue)` would have to be coinductive. 

However that is because the former could represent a non-terminating computation whose return type is an error. But that should not be an issue for this change, since I believe the semantics never builds such a weird computation. 

In particular, if you make the change in signature to `eval_exp`, the case of `OP_IBinop` should never require to do one such thing. You would have inductively two `err (itree IO dvalue)`, and would therefore never have to crawl down a tree to recover the error, it should always be at the top.

I might be missing a detail myself, but therefore think as long as the change is propagated everywhere, it should be fine.

**Comment by Chobbes** [comment]
> In particular, if you make the change in signature to `eval_exp`, the case of `OP_IBinop` should never require to do one such thing. You would have inductively two `err (itree IO dvalue)`, and would therefore never have to crawl down a tree to recover the error, it should always be at the top.

Yep! But, I think the detail being missed here is that `eval_iop : ibinop -> dvalue -> dvalue -> err dvalue`, so if I lifted `eval_iop` I would get a `Trace (err dvalue)`. @YaZko does that change anything?

> You can not write this function in Coq. Co-inductive functions must produce values of co-inductive types.

Exactly what I was thinking! Boo :(.

> On a higher-level note. This change means a fundamental change to the meaning of terms. In the current definition, errors are dynamic, e.g. integer overflow could be an error. In the proposed changes to, errors can only be static.

This is my understand as well, so I'm glad I'm on the right page there. I believe the idea is that we would factor out all of the static errors into the outside error monad, but I think in thinking of this we neglected our dynamic errors (or maybe we were planning to discriminate by these things somehow? @Zdancewic?)

> If this is really the case, then the functions that construct these values are likely fixpoints, so you just need to change them (if they are not, there is some bug in the semantics).

Sorry, let me see if I understand, you mean that if the errors are really static then the functions which constructed the values are likely fixpoints? I think I am getting confused because I am not certain what "values" are being referred to in this context, but `eval_exp` is a fixpoint?

```
Fixpoint eval_exp (top:option dtyp) (o:exp) {struct o} : err (Trace dvalue)
```

**Comment by Chobbes** [comment]
@Zdancewic gotcha, so failure may still be an effect in the iTree monad, or we may just make all of these failures produce undef / poison. What I got out of the meeting was "failure outside of the iTree", so perhaps I misinterpreted that. So the idea is that in LLVM semantics you're not going to get an "error" exactly, you're just going to get undef or poison values?

> The current implementation kind of conflates these two things, but I think that having a cleaner separation might make reasoning about the semantics easier. A symptom of this conflation might be the partiality of `eval_iop`. It's type might be better defined as "total" for dynamic values, where, instead of producing an error, it produces DVALUE_Poison.

I think in LLVM this arises as a type error, so it seems like it would be sort of disingenuous to give this the result of `DVALUE_Poison`. Perhaps we should only reason about well typed LLVM programs, though, which would mean that these bad cases would go away and don't matter?

**Comment by Zdancewic** [comment]
Yeah -- the semantics should only need to do anything reasonable for well-formed LLVM programs, so the semantics can be partial (or bogus) on those that aren't. The question is how to treat all of the different failure modes:

1. our semantics is incomplete (e.g. missing feature)

2. the LLVM program is ill-formed (e.g. what happens when we look up an variable and don't find it in the environment, or the program is ill-typed)

3. LLVM semantics represent the "undefinedness".  (e.g. when loading from unallocated memory, you get undef)

For (3) we don't have a choice -- we follow the LLVM semantics.  For 1 and 2 we currently use the "Fail" trace value everywhere, even for the static errors that could potentially be represented with the err type.  I had been thinking that maybe it would make sense to try to disentangle the static errors from the dynamic ones, but, it might not be worth it.  Either way, we'll have to preface our theorems with a (coinductive) predicate that says we only care about behaviors of the semantics that don't contain Fail...

Given all of that, maybe we _don't_ really care too much about moving parts of the semantics into the err monad instead of the (IO + faileE) monad...

**Comment by Chobbes** [comment]
> Given all of that, maybe we _don't_ really care too much about moving parts of the semantics into the err monad instead of the (IO + faileE) monad...

This is my concern. It makes sense that if we can catch all ill-formed programs beforehand we can extract a lot of this into the external err monad... In this case we are guaranteed to not generate traces of ill-formed programs. This sounds great, but you probably want a predicate that it's a well formed program for use in proofs anyway? Unless you give everything dependent types so it's guaranteed to be well-formed / typed by the construction of the program? So if you need an external well-formed / typed predicate anyway, I'm not sure factoring this all out saves us anything?

**Comment by gmalecha** [comment]
Tangentially following this thread.

The purist in me thinks it would be worthwhile to separate an error monad from an error effect. The error effect is unavoidable, e.g. call an undefined function pointer. The error monad can represent ill-typed terms and such.

I'm not sure how easy it will be to use a co-inductive predicate that a term is well-typed, but it would be interesting.

**Comment by Chobbes** [comment]
> I'm not sure how easy it will be to use a co-inductive predicate that a term is well-typed, but it would be interesting.

I currently don't have much experience actually using coinduction, so anything that I say should be taken with a grain of salt. I'm not aware of what co-inductive dragons lie ahead, haha.

Although, maybe I'm not understanding something here... Our programs are still inductively defined, and wouldn't a well-formed / well-typed predicate be on the programs themselves, and not the coinductive traces which are produced from running the programs?

I think you might be right that it's a cleaner separation to, say, separate out the type checking and then bundle those errors into the external error monad, as they are not errors related to running a program. But I think regardless when doing proofs about programs you would only want to prove things about well typed programs, so I would think that you would need such a predicate, and you would want a proof that every program that passes the type checker and doesn't end up in the error monad is well typed, right?

**Comment by Chobbes** [comment]
So, the conclusion of this is that we think it makes sense to use a coinductive "doesn't fail" predicate to exclude programs that we don't care about reasoning about. This predicate will essentially serve as an implicit "well-formed / well-typed" predicate. I guess in theory we could even prove that these correspond if we want to make sure we are reasoning about the programs that we think we are?

Either way, I'm closing this issue for now (feel free to comment / reopen, though).
