### ISSUE TITLE
float literals

### ISSUE THREAD

**Issue by vzaliva** [vellvm/vellvm#95]
The problem is best illustrated by the following example:

```
llc -relocation-model=pic -asm-verbose -O0 test_binop_plus.ll
llc: test_dynwin32.ll:2:43: error: floating point constant invalid for type
@D = internal constant [3 x float] [float 76756783.5125, float -243791519.156, float -197089434.476], align 16
                                          ^
Makefile:22: recipe for target 'test_dynwin32.s' failed
```

This code is pretty-printed from LLVM AST. The problem is that `76756783.5125` could not be represented as an exact floating point value. (You can check here: https://www.h-schmidt.net/FloatConverter/IEEE754.html). The IR reference states:

> "The assembler requires the exact decimal value of a floating-point constant. For example, the assembler accepts 1.25 but rejects 1.3 because 1.3 is a repeating decimal in binary."

The question is how such constant appeared in the first place. The value in question was generated from `EXP_Float` with the following code:

`EXP_Float (Float.of_single b32)` where `b32` has type `binary32`

It was done as a workaround for https://github.com/vellvm/vellvm/issues/73

To sum it up, we started with a valid 32-bit floating point value, which we converted to 64-bit floating point constant. This constant was pretty-printed as an ASCII string which does not represent exact 32-bit floating point value.

One possible explanation (source: https://cs.stackexchange.com/questions/56976/whether-assigning-of-single-precision-ieee754-float-to-double-is-reversible ) is while the 64-bit value is the same as 32-bit, but when printed it is rendered to a different decimal string which could not be parsed back without precision loss. In other words:

- `binary32 -> binary64 -> binary32`  - **OK**
- `binary32 -> binary64 -> string -> binary32` -  **Precision loss!**

If my hypothesis is correct it could be fixed by either making sure 32-bit floats are properly pretty printed, or by revisiting https://github.com/vellvm/vellvm/issues/73 and using proper binary32 to store 32-bit floating point constants internally.

**Comment by Zdancewic** [comment]
Interesting!  It seems like patching the pretty-printer is the right way to go.  

Unfortunately, this isn't quite so straightforward to fix as you might want because OCaml doesn't have a 32bit floating point value.  This means that we probably need to call out to a small C function that does the right thing.  We'll also have to add a bit of case analysis to the pretty printer to determine whether to print an EXP_Float value as either a single or double precision string representation.

We'll look into this over the next few days!

**Comment by Zdancewic** [comment]
Calvin suggested another easy change that might fix this -- we can probably print single-precision floating point numbers in their hexadecimal representations.  This is supported by OCaml and might be more general anyway, since it also supports NaN, etc.

**Comment by vzaliva** [comment]
I agree that hex printing is the best way to represent floating point constants in pretty printing.

I am still a bit uneasy about not using appropriate binary float types in Coq to represent constants and using float64 for both 32 and 64-bit values. It still seems like a small unnecessary optimization. Not sure how much we gaining while losing tight typing. This could also present nuisance in proofs related to LLVM semantics using floats.

**Comment by Zdancewic** [comment]
I'm not sure what you mean about not using appropriate binary float types in Coq.  The two dynamic values are `DVALUE_Float`, which uses the Coq `Float32` library, and `DVALUE_Double`, which uses the Coq `Float` (64-big) library.  The only place where we conflate the two is in the parser and abstract syntax, where both are represented as `EXP_Float f`.  As soon as we interpret a floating-point literal for the purposes of computation, it gets converted to the correctly typed representation.  

The reason why we do it that way is that, when parsing, we don't (easily) have the information about what bit-width a literal should be treated as.  To do that properly would mean that we have to make the parser more context-dependent.  (Also, since OCaml doesn't support 32-bit floats, it's not clear what datatype we would use to represent the parsed values; currently we do: `coqfloat_of_float (float_of_string s)`.)

**Comment by vzaliva** [comment]
One of the problems is that I can construct an AST with `EXP_Float` expression which represents 32-bit float but contains a value which could not be converted to 32-representation without precision loss.
For example, I do not think we can prove the following: 

```
forall (x:EXP_Float),
    let (v:DVALUE_Float) := eval_exp DTYPE_Float x in
        EXP_Float (Float.of_single (ll_float v)) = x
```

Informally `EXP_float` is not an inverse of `eval_exp`. I think it might prevent us from doing some optimizations based on AST, for example computing constant expressions like `1.0 + 2.0` and replacing it with `3.0`.

**Comment by Zdancewic** [comment]
I see.  The lemma you state is definitely not provable.  You're right that we'd have to add some preconditions about the literals to prove optimizations of the kind you suggest.

To do better, we'd have to disambiguate 32bit from 64bit floats somewhere shorty after (or maybe during?) parsing.  This interacts with @Chobbes pretty-printing fix.

**Comment by Chobbes** [comment]
@Zdancewic maybe it makes sense to just do a pass after parsing (when we have all the typing information) to change float64s to float32s where necessary? (As well as all the other weird 80-bit and 128-bit floating point values, which I believe we have to print differently?)

I do feel that it's kind of scary representing single precision floats as doubles in VELLVM.

**Comment by Zdancewic** [comment]
I'll take a crack at adding this pass right now, just to see how bad it gets...  We should be able to do this in the parser, I think.

**Comment by Zdancewic** [comment]
The pull request I just merged addresses most of this issue, so I'll close this thread.  We still have the "sound" 64bit->32bit conversion to do (probably on the Coq side.
